apiVersion: apps/v1
kind: Deployment
metadata: 
  name: java-user
  labels:
    app: chartissimo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: chartissimo
  template:
    metadata:
      labels:
        app: chartissimo
    spec:
      containers:
      - name: java-user
        image: localhost:32000/java-user:1448
        ports: 
        - containerPort: 8080


---
apiVersion: v1
kind: Service
metadata:
  name: java-user
spec:
  selector:
    app: chartissimo
  type: LoadBalancer
  ports:
    - protocol: TCP
      name: java-user
      port: 8080
      targetPort: 8080
      nodePort: 30005

# ---
# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: frontend-configmap
# data:
#   REACT_APP_API_PORT: "4000"