apiVersion: apps/v1
kind: Deployment
metadata: 
  name: api
  labels:
    app: chartissimo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: chartissimo
  template:
    metadata:
      labels:
        app: chartissimo
    spec:
      containers:
      - name: api
        image: localhost:32000/api:1501
        ports: 
        - containerPort: 5000


---
apiVersion: v1
kind: Service
metadata:
  name: api
spec:
  selector:
    app: chartissimo
  type: LoadBalancer
  ports:
    - protocol: TCP
      name: api
      port: 5000
      targetPort: 5000
      nodePort: 30001

# ---
# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: frontend-configmap
# data:
#   REACT_APP_API_PORT: "4000"