apiVersion: apps/v1
kind: Deployment
metadata: 
  name: auth
  labels:
    app: chartissimo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: chartissimo
  template:
    metadata:
      labels:
        app: chartissimo
    spec:
      containers:
      - name: auth
        image: localhost:32000/auth:0150
        ports: 
        - containerPort: 4000



---
apiVersion: v1
kind: Service
metadata:
  name: auth
spec:
  selector:
    app: chartissimo
  type: LoadBalancer
  ports:
    - protocol: TCP
      name: auth
      port: 4000
      targetPort: 4000
      nodePort: 30002


# ---
# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: frontend-configmap
# data:
#   REACT_APP_API_PORT: "4000"