apiVersion: apps/v1
kind: Deployment
metadata: 
  name: frontend
  labels:
    app: chartissimo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: chartissimo
  template:
    metadata:
      labels:
        app: chartissimo
    spec:
      containers:
      - name: frontend
        image: localhost:32000/front:port
        ports: 
        - containerPort: 80
        # env:
        #   - name: REACT_APP_API_PORT
        #     valueFrom: 
        #       configMapKeyRef:
        #         name: frontend-configmap
        #         key: REACT_APP_API_PORT
        #   - name: REACT_APP_AUTH_PORT
        #     valueFrom: 
        #       configMapKeyRef:
        #         name: frontend-configmap
        #         key: REACT_APP_AUTH_PORT
        #   - name: REACT_APP_BACKEND_IP
        #     valueFrom:
        #       configMapKeyRef:
        #         name: frontend-configmap
        #         key: REACT_APP_BACKEND_IP
        envFrom:
          - configMapRef:
              name: frontend-configmap

---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  selector:
    app: chartissimo
  type: LoadBalancer
  ports:
    - protocol: TCP
      name: http
      port: 80
      targetPort: 80
      nodePort: 30000


---
apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-configmap
data:
  REACT_APP_API_PORT: "5000"
  REACT_APP_AUTH_PORT: "4000"
  REACT_APP_BACKEND_IP: "localhost"