apiVersion: apps/v1
kind: Deployment
metadata: 
  name: data
  labels:
    app: chartissimo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: chartissimo
  template:
    metadata:
      labels:
        app: chartissimo
    spec:
      containers:
      - name: data
        image: localhost:32000/java-data:0150
        ports: 
        - containerPort: 5000