apiVersion: apps/v1
kind: Deployment
metadata: 
  name: api
  labels:
    app: chartissimo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: chartissimo
  template:
    metadata:
      labels:
        app: chartissimo
    spec:
      containers:
      - name: api
        image: localhost:32000/api:1501
        ports: 
        - containerPort: 5000

